name: Build installer package

on:
  workflow_dispatch:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - github-action

jobs:
  build-and-release:
    runs-on:
      labels: oc-runner
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: github-action
      - name: Decrypt Secrets
        run: nix develop .#gitCrypt --command decrypt ${{ secrets.GIT_CRYPT_KEY }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
          diagnostic-endpoint: ""
      - name: Build package
        run: nix build -L .#installerPackage
