name: Build release

on:
  workflow_dispatch:

jobs:
  build-package-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: read
    steps:
      - uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ github.token }}
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          extra-conf: |
            system = aarch64-linux
            trusted-users = *
            experimental-features = nix-command flakes
            extra-substituters = https://cache.lix.systems https://nixos-asahi.cachix.org
            extra-trusted-public-keys = cache.lix.systems:aBnZUw8zA7H35Cz2RyKFVs3H4PlGTLawyY5KRbvJR8o= nixos-asahi.cachix.org-1:CPH9jazpT/isOQvFhtAZ0Z18XNhAp29+LLVHr0b2qVk=
      - name: Setup qemu
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
          sudo mount -o remount,size=30G /run
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build .#asahiPackage
        id: build-package
        run: |
          sudo systemctl restart nix-daemon.service
          sudo systemctl daemon-reload
          sudo nix build -L .#packages.aarch64-linux.asahiPackage
      - name: upload to bucket
        run: |
          sudo apt-get install -y python3 python3-pip
          ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}; export ACCESS_KEY_ID
          SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}; export SECRET_ACCESS_KEY
          BUCKET=${{ secrets.BUCKET }}; export BUCKET
          REGION='auto'; export REGION
          ./scripts/upload.sh
      # - name: Release
      #   uses: softprops/action-gh-release@v2.0.8
      #   with:
      #     tag_name: release-${{ steps.build-package.outputs.release_date }}
      #     name: NixOS Asahi-Installer Package ${{ steps.build-package.outputs.release_date }}
      #     files: ./src/nixos-asahi-${{ steps.build-package.outputs.release_date }}.zip
      #     draft: true
