name: Build installer package

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"
    branches:
      - github-action
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: self-hosted
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - name: Decrypt Secrets
        run: |
          sudo apt-get update && sudo apt-get install -y git-crypt
          base64 -d <<< ${{ secrets.GIT_CRYPT_KEY }} | git-crypt unlock -
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: '${{ github.token }}'
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
          diagnostic-endpoint: ""
      - name: Build package
        run: nix build -L .#packages.aarch64-linux.installerPackage