name: Build package and release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on:
      labels: oc-runner
    permissions:
      id-token: "write"
      contents: "write"
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: cachix/cachix-action@v16
        with:
          name: nixos-asahi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build package
        run: nix build -L .#installerPackage

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            result/nixos-asahi-*.zip
            result/installer_data-*.json

      - name: Upload to CDN
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          touch ./.env
          cat > .env <<EOF
          export ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}
          export BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          export ENDPOINT_URL=${{ secrets.ENDPOINT_URL }}
          export SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
          EOF

          nix run .#upload
