name: Build release

on:
  workflow_dispatch:

jobs:
  build-package-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@main
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ github.token }}
          source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
          extra-conf: |
            system = aarch64-linux
            experimental-features = nix-command flakes
            keep-outputs = true
            keep-derivations = true
            substituters = https://cache.lix.systems https://nixos-asahi.cachix.org
            trusted-public-keys = cache.lix.systems:aBnZUw8zA7H35Cz2RyKFVs3H4PlGTLawyY5KRbvJR8o= nixos-asahi.cachix.org-1:CPH9jazpT/isOQvFhtAZ0Z18XNhAp29+LLVHr0b2qVk=
      - name: Setup qemu
        run: |
          sudo apt install -y qemu-system-aarch64 qemu-efi binfmt-support qemu-user-static
          sudo mount -o remount,size=30G /run
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build .#asahiPackage
        id: build-package
        run: |
          if nix build -L .#packages.aarch64-linux.asahiPackage
          then
            mkdir src
            cp $(readlink result)/{.root_part_size,.release_date,nixos-asahi-*.zip} src
            chmod 644 src/*
            echo "release_date=$(cat src/.release_date)" >> "$GITHUB_OUTPUT"
          fi
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: release-${{ steps.build-package.outputs.release_date }}
          name: NixOS Asahi-Installer Package ${{ steps.build-package.outputs.release_date }}
          files: ./src/nixos-asahi-${{ steps.build-package.outputs.release_date }}.zip
          draft: true
      - name: Upload to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: src
          destination-dir: ./
