name: Build package and release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on:
      labels: oc-runner

    permissions:
      id-token: "write"
      contents: "write"

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: cachix/cachix-action@v16
        with:
          name: nixos-asahi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build metapackage
        run: nix-fast-build --eval-workers 24 --no-nom --skip-cached

      - name: Release
        uses: softprops/action-gh-release@v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            result-aarch64-linux/nixos-asahi-*-btrfs.json
            result-aarch64-linux/nixos-asahi-*-btrfs.zip
            result-aarch64-linux/installer_data-*-ext4.json
            result-aarch64-linux/nixos-asahi-*-ext4.zip

      - name: Upload to CDN
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          touch ./.env
          cat > .env <<EOF
          export ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}
          export BASE_URL="https://cdn.qeden.dev"
          export BUCKET_NAME="nixos-asahi"
          export ENDPOINT_URL=${{ secrets.ENDPOINT_URL }}
          export SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
          EOF

          nix run .#upload -- ./result-aarch64-linux
