name: Build installer package

on:
  workflow_dispatch:
  push:
    branches:
      - github-action

jobs:
  build:
    runs-on:
      labels: oc-runner
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false
          diagnostic-endpoint: ""

      - name: Decrypt Secrets
        run: nix develop .#gitCrypt --command decrypt ${{ secrets.GIT_CRYPT_KEY }}

      - name: Build package
        run: nix build -L .#installerPackage

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-asahi-${{ github.ref_name }}
          path: result/nixos-asahi-*.zip